Repository ietebitmesra/HacktoberFest-2020, pull requests merged in 2020-10, with the labels that each got.

#72 Task1-GaurangAgarwal
  Task1/img/GaurangAgarwal.jpg
  Task1/index.html
Labels: hacktoberfest

#90 Corrected index.html
  Task1/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#107 Timer starts when first letter of first word is stuck- Deepak
  Task3/js/updateText.js
Labels: hacktoberfest-accepted

#103 Change the condition to check the special character.
  .idea/.gitignore
  .idea/HacktoberFest-2020.iml
  .idea/modules.xml
  .idea/vcs.xml
  Task3/js/updateText.js
Labels: hacktoberfest-accepted

#112 Task 3 Error count should not decrease #94 and other issues
  Task3/css/style.css
  Task3/js/updateText.js
Labels: hacktoberfest-accepted

#117 Showing improvements for particular session/#95
  Task3/css/style.css
  Task3/js/updateText.js
Labels: hacktoberfest-accepted
